name: Docs Linter

on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  NODE_VERSION: 16

jobs:
  lint:
    name: JS & CSS & VUE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # https://github.com/actions/checkout/releases/tag/v3.1.0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # https://github.com/actions/setup-node/releases/tag/v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install Documentation dependencies
        run: |
          cd docs/ && npm ci --no-audit

      - name: Install Handsontable dependencies
        run: |
          npm ci --no-audit

      - name: Lint
        run: |
          cd docs/ && npm run docs:lint
