name: Docs Production Deployment

env:
  GHA_DOCKER_TAG: docker.pkg.github.com/${{ github.repository }}/handsontable-documentation

on:
  push:
    branches:
      - 'prod-docs/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./docs/

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2

      - uses: actions/github-script@7a5c598405937d486b0331594b5da2b14db670da # https://github.com/actions/github-script/releases/tag/v6.1.0
        id: get-docs-version
        with:
          script: return context.ref.match(/^refs\/heads\/prod\-docs\/(\d+\.\d+)$/)[1] ?? '';
          result-encoding: string

      - name: Validate Docs version
        run: if [ -z "${{steps.get-docs-version.outputs.result}}" ]; then echo "Docs version is empty"; exit 1; fi

      - name: Docker login into GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${GITHUB_ACTOR} --password-stdin https://docker.pkg.github.com
      - name: Dependencies
        run: |
          npm ci
      - name: Docker build
        run: |
          npm run docs:docker:build:production
      - name: Docker tags
        run: |
          docker tag docs-md:production $GHA_DOCKER_TAG":v${{steps.get-docs-version.outputs.result}}"
          docker tag docs-md:production $GHA_DOCKER_TAG":v${{steps.get-docs-version.outputs.result}}-${{ github.sha }}"
      - name: Docker push production into GHCR
        run: |
          docker push $GHA_DOCKER_TAG":v${{steps.get-docs-version.outputs.result}}"
      - name: Docker push SHA tagged into GHCR
        run: |
          docker push $GHA_DOCKER_TAG":v${{steps.get-docs-version.outputs.result}}-${{ github.sha }}"
      - name: Deploy the Docs image
        uses: satak/webrequest-action@6127ff14e9269df0d49bcaec84f948dc8b50df1f # v1.2.4
        with:
          url: 'https://docs.handsontable.com/api/deploy'
          method: POST
          username: ${{secrets.DOCS_DEPLOYMENT_USER}}
          password: ${{secrets.DOCS_DEPLOYMENT_PASSWORD}}
          payload: '{"token": "${{secrets.DOCS_DEPLOYMENT_TOKEN}}","docsVersion": "${{steps.get-docs-version.outputs.result}}"}'
